version: 2
jobs:
  checkout:
    docker:
    - image: circleci/node:8.12.0
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
        - .

  build:
    docker:
    - image: circleci/node:8.12.0
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        command: yarn install
    - save_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
    - persist_to_workspace:
        root: .
        paths:
        - .

  test:
    docker:
    - image: circleci/node:8.12.0
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Run linter
        command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
    - checkout
    - build:
        requires:
          - checkout
    - test:
        requires:
          - build
    - publish:
        requires:
          - test
